@Library('jenkins-pipeline-lib@v1') _

import com.example.devops.jenkins.Utilities

def utils = new Utilities(this)

node {
  stage("Checkout SCM") {
    checkout scm
  }

  utils.hello 'Aloha!!'

  stage("Initialization"){
    println "Reading Jenkins configuration  file"
    def config = utils.get_config(env.WORKSPACE + "/jenkins_config.yaml")
    println config["app_name"]
  }

  stage("Building app") {
    utils.build(config)
  }

  stage("Testing App"){
    utils.test(config)

  }

  stage("Deploying app"){
    utils.deploy(config)
  }

  stage("SmokeTest"){
    utils.smoketest(config)
  }
}
