@Library('jenkins-pipeline-lib@master') _

import com.example.devops.jenkins.Utilities

def utils = new Utilities(this)
node {

  def config
  def workspace = env.WORKSPACE

  stage("Checkout SCM") {
    checkout scm
  }

  utils.hello 'Aloha!!'

  stage("Initialization"){
    println "Reading Jenkins configuration  file"
    config = utils.get_config(workspace + "/jenkins_config.yaml")
    println config["app_name"]
  }

  stage("Building app") {
    utils.build(config,workspace)
  }

  stage("Testing App"){
    utils.test(config,workspace)

  }

  stage("Deploying app"){
    utils.deploy(config,workspace)
  }

  stage("SmokeTest"){
    utils.smoketest(config,workspace)
  }
}
