@Library('jenkins-pipeline-lib@v1') _

import com.example.devops.jenkins.Utilities

def utils = new Utilities(this)

node {
  stage("Checkout SCM") {
    checkout scm
  }
  utils.hello 'Aloha!!'
  stage("Initialization"){
    println "Reading Jenkins configuration  file"
    config = utils.get_config("./jenkins_config.yaml")
    println $config
  }
}
